### ISSUE TITLE
[Elao - App] MongoDB support

### ISSUE THREAD

**Issue by nervo** [manala/manala-recipes#126]
Docker containers
```
          - name: mongo-express
            image: mongo-express
            state: absent
            restart_policy: unless-stopped
            #env:
              # Default docker host ip
              # host.docker.internal ?
              # gateway.docker.internal ?
            #  REDIS_1_HOST: 172.17.0.1
            ports:
              - 1981:80
```
