### ISSUE TITLE
Integration / JenkinsFile : Allow task to fail

### ISSUE THREAD

**Issue by benji07** [manala/manala-recipes#5]
It would be great if we can configure the task of the integration to fail without stopping the pipeline

For exemple, we can check phpstan but not breaking the build even if the phpstan task fail

Something like this:

```yaml
tasks:
    - shell: make install@integration
      allowFailure: true
```
